name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t myapp:test .

      - name: Run Docker container
        run: docker run -d -p 5173:5173 myapp:test

      - name: List running containers
        run: docker ps

      - name: Check Docker container logs
        run: docker logs $(docker ps -q --filter ancestor=myapp:test)

      - name: Test application endpoint
        run: curl -f http://localhost:5173 || exit 1
