name: CI docker

on:
  push:
    branches:
      - 'main'

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Get repo code
      uses: actions/checkout@v2
    - name: Set up docker file
      uses: docker/setup-buildx-action@v1
    - name: Sign in to docker hub
      uses: docker/login-action@v1
      with: 
        username: egoresipenka@gmail.com
        password: bout2005
    - name: Build and run Docker image
      run: |
        docker build -t myapp:test .
        docker run --rm myapp:test